In [28]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import Imputer, LabelEncoder, OneHotEncoder
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
# from sklearn.cross_validation import train_test_split 会报错https://blog.csdn.net/cheneyshark/article/details/78640887
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# 导入数据集，获取X， Y
dataset = pd.read_csv('../datasets/Data.csv')
X = dataset.iloc[ : , :-1].values
Y = dataset.iloc[ : , 3].values

# X 中有NAN数据，替换之
imp = Imputer(missing_values=np.nan , strategy='mean', axis=0)
imp.fit(X[ : , 1:3])
X[ : , 1:3] = imp.transform(X[ : , 1:3])

# 将X第一列数据的单词，对应到数字标签
labelencoder_X = LabelEncoder()
X[ : , 0] = labelencoder_X.fit_transform(X[ : , 0])

# 将X第一列数据的单词，对应到数字标签
labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y)

# 对第一列进行OneHot编码，也就是用France Spain Germany...转换的那一列，总共有三类，转换成3列数据用OneHot表示
onehotencoder = OneHotEncoder(categorical_features = [0])
X = onehotencoder.fit_transform(X).toarray()

# 按照8:2的比例对数据集进行快速打乱，分为训练集和测试集
X_train, X_test, Y_train, Y_test = train_test_split( X , Y , test_size = 0.4, random_state = 0)

# 针对每个特征值来做去均值和方差的归一化操作
sc_X = StandardScaler()
X_test = sc_X.fit_transform(X_test)
X_train = sc_X.fit_transform(X_train)

print X_train, Y_train
print X_test, Y_test

[[-1.          0.          1.         -1.72380603 -1.26408415]
 [-1.          0.          1.          0.04734201 -0.8941083 ]
 [ 1.          0.         -1.          1.43418434  1.60322868]
 [-1.          0.          1.         -0.0696206  -0.06166264]
 [ 1.          0.         -1.          0.83266236  0.95577094]
 [ 1.          0.         -1.         -0.52076208 -0.33914453]] [1 0 1 0 0 1]
[[-0.57735027  0.57735027  0.         -1.28661606 -1.24074912]
 [-0.57735027  0.57735027  0.          1.49525651  1.53895492]
 [-0.57735027  0.57735027  0.          0.10432022 -0.3035309 ]
 [ 1.73205081 -1.73205081  0.         -0.31296066  0.0053251 ]] [0 0 1 1]
